---
title: "Investigate structure"
author: "Devon DeRaad"
date: "9/18/2020"
output: html_document
---

```{r}
#geographic investigation
#17 December 2020
library(vcfR)
library(ggplot2)
library(gridExtra)
library(ggridges)
library(adegenet)
library(dplyr)
library(StAMPP)
library(gplots)
library(scatterpie)
library(geosphere)
library(ggtree)
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```

```{r, out}
#read in vcf
vcfR <- read.vcfR("~/Desktop/hipposideros/filtered.vcf.gz")

#convert to genlight
gen<- vcfR2genlight(vcfR)

#read in locality info for samples
locs<-read.csv("~/Desktop/hipposideros/hipposideros.sampling.csv")
#subset locs to include only samples that passed filtering, and have been retained in the vcf
locs<-locs[locs$id %in% gen@ind.names,]

#check that our sampling df matches our vcf file
gen@ind.names == locs$id

#check number of samples per species
table(locs$species)

#reorder gen by species assignments
gen<-gen[c(1:3,7:12,30:32,34:36,50,52,54,
           4:6,14:19,27,
           22:25,28,29,33,37,38,45:49,51,
           13,39:44,53,55,
           26,
           20,21),]
#order by species assingments
locs<-locs[c(1:3,7:12,30:32,34:36,50,52,54,
           4:6,14:19,27,
           22:25,28,29,33,37,38,45:49,51,
           13,39:44,53,55,
           26,
           20,21),]
rownames(locs)<-1:55

#make full map
pac<-map_data("world")
#
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="grey", col="black", cex=.1)+
  coord_sf(xlim = c(143, 165), ylim = c(-13, -3)) + 
  geom_jitter(data = locs, aes(x = Longitude, y = Latitude, col=species), alpha =.6, show.legend=TRUE, cex=3,
              width=.2,height=.2) +
  theme_classic()+
  scale_color_manual(values=viridis::plasma(n=7))+
  scale_size_continuous(range = c(2,8))+
  guides(colour = guide_legend(override.aes = list(size = 4), 
         order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(nrow = 1, order = 2))+
  theme(legend.position = c(0.8, 0.5), legend.justification = c(0.01, 0.01),
        legend.background = element_blank())

```

```{r, fig.height=8, fig.width=8}
#calculate divergence btwn samples
gen@pop<-locs$species
inds<-stamppNeisD(gen, pop = FALSE)

#plot tree 
tree <- nj(inds)

#plot ggtree
ggtree(tree)+
  geom_tiplab(cex=2)+
  xlim(0, .55)
```

```{r, fig.height = 6, fig.width = 8, fig.align = "center"}
#subset genlight to only diadema and dinops
di.gen<-new("genlight",(as.matrix(gen)[locs$species == "diadema" | locs$species == "dinops", ]))
#remove misindentified sample
di.gen<-new("genlight",(as.matrix(di.gen)[c(1:23,25:28), ]))
#subset loc info
di.locs<-locs[locs$species == "diadema" | locs$species == "dinops", ]
#remove misindentified sample
di.locs<-di.locs[c(1:23,25:28), ]

di.locs<-droplevels(di.locs)
#plot map of species
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="grey", col="black", cex=.1)+
  coord_sf(xlim = c(143, 165), ylim = c(-13, -3)) + 
  geom_jitter(data = di.locs, aes(x = Longitude, y = Latitude, col=species), alpha =.5, show.legend=TRUE, cex=5,
              width=.2,height=.2) +
  theme_classic()+
  scale_color_manual(values=gg_color_hue(2))+
  scale_size_continuous(range = c(2,8))+
  guides(colour = guide_legend(override.aes = list(size = 4), 
         order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(nrow = 1, order = 2))+
  theme(legend.position = c(0.8, 0.5), legend.justification = c(0.01, 0.01),
        legend.background = element_blank())

#PCA of species
di.pca<-glPca(di.gen, nf=6)

#pull pca scores out of df
di.pca.scores<-as.data.frame(di.pca$scores)
di.pca.scores$species<-di.locs$species

#ggplot color by species
ggplot(di.pca.scores, aes(x=PC1, y=PC2, color=species)) +
  geom_point(cex = 5, alpha=.5)+
  theme_classic()

#colored by island
x<-gsub(".*_H_","",rownames(di.pca.scores))
x<-gsub(".*_","",x)
di.pca.scores$island<-x
ggplot(di.pca.scores, aes(x=PC1, y=PC2, color=island)) +
  geom_point(cex = 5, alpha=.5)+
  theme_classic()
ggplot(di.pca.scores, aes(x=PC1, y=PC2, color=island, shape=species)) +
  geom_point(cex = 5, alpha=.5)+
  xlim(c(-2.5,1.5))+
  ylim(c(-2.5,2.5))+
  theme_classic()

```

```{r, fig.height = 6, fig.width = 8, fig.align = "center"}
#subset genlight to only calcaratus
cal.gen<-new("genlight",(as.matrix(gen)[locs$species == "calcaratus", ]))
#subset loc info
cal.locs<-locs[locs$species == "calcaratus", ]
cal.locs<-droplevels(cal.locs)

#plot map of species
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="grey", col="black", cex=.1)+
  coord_sf(xlim = c(143, 165), ylim = c(-13, -3)) + 
  geom_jitter(data = cal.locs, aes(x = Longitude, y = Latitude, col=species), alpha =.5, show.legend=TRUE, cex=5,
              width=.2,height=.2) +
  theme_classic()+
  scale_color_manual(values=gg_color_hue(2))+
  scale_size_continuous(range = c(2,8))+
  guides(colour = guide_legend(override.aes = list(size = 4), 
         order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(nrow = 1, order = 2))+
  theme(legend.position = c(0.8, 0.5), legend.justification = c(0.01, 0.01),
        legend.background = element_blank())

#PCA of species
cal.pca<-glPca(cal.gen, nf=6)

#pull pca scores out of df
cal.pca.scores<-as.data.frame(cal.pca$scores)
#colored by island
x<-gsub(".*_H_","",rownames(cal.pca.scores))
x<-gsub(".*_","",x)
cal.pca.scores$island<-x

#ggplot color by island
ggplot(cal.pca.scores, aes(x=PC1, y=PC2, color=island)) +
  geom_point(cex = 5, alpha=.5)+
  theme_classic()
```

```{r, fig.height = 6, fig.width = 8, fig.align = "center"}
#subset genlight to only calcaratus
cer.gen<-new("genlight",(as.matrix(gen)[locs$species == "cervinus", ]))
#subset loc info
cer.locs<-locs[locs$species == "cervinus", ]
cer.locs<-droplevels(cer.locs)

#plot map of species
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="grey", col="black", cex=.1)+
  coord_sf(xlim = c(143, 165), ylim = c(-13, -3)) + 
  geom_jitter(data = cer.locs, aes(x = Longitude, y = Latitude, col=species), alpha =.5, show.legend=TRUE, cex=5,
              width=.2,height=.2) +
  theme_classic()+
  scale_color_manual(values=gg_color_hue(2))+
  scale_size_continuous(range = c(2,8))+
  guides(colour = guide_legend(override.aes = list(size = 4), 
         order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(nrow = 1, order = 2))+
  theme(legend.position = c(0.8, 0.5), legend.justification = c(0.01, 0.01),
        legend.background = element_blank())

#PCA of species
cer.pca<-glPca(cer.gen, nf=6)

#pull pca scores out of df
cer.pca.scores<-as.data.frame(cer.pca$scores)
#colored by island
x<-gsub(".*_H_","",rownames(cer.pca.scores))
x<-gsub(".*_","",x)
cer.pca.scores$island<-x

#ggplot color by island
ggplot(cer.pca.scores, aes(x=PC1, y=PC2, color=island)) +
  geom_point(cex = 5, alpha=.5)+
  theme_classic()
```

```{r, fig.height = 6, fig.width = 8, fig.align = "center"}
#calculate divergence btwn pops within each species
cal.locs$pop<-gsub(".*_H_","",cal.locs$id)
cal.gen@pop<-as.factor(cal.locs$pop)

cal.heat<-stamppNeisD(cal.gen, pop = TRUE)
colnames(cal.heat)<-rownames(cal.heat)
cal.heat <- reshape::melt(cal.heat)
ggplot(data = cal.heat, aes(x=X1, y=X2, fill=value)) + 
  geom_tile()+
  scale_fill_gradient2(low = "white", high = "red", space = "Lab", name="Nei's D") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r, fig.height = 6, fig.width = 8, fig.align = "center"}
#calculate divergence btwn pops within each species
cer.locs$pop<-gsub(".*_H_","",cer.locs$id)
cer.gen@pop<-as.factor(cer.locs$pop)

cer.heat<-stamppNeisD(cer.gen, pop = TRUE)
colnames(cer.heat)<-rownames(cer.heat)
cer.heat <- reshape::melt(cer.heat)
ggplot(data = cer.heat, aes(x=X1, y=X2, fill=value)) + 
  geom_tile()+
  scale_fill_gradient2(low = "white", high = "red", space = "Lab", name="Nei's D") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r, fig.height = 6, fig.width = 8, fig.align = "center"}
#investigate how divergent pops are
di.locs$pop<-gsub(".*_H_","",di.locs$id)
di.gen@pop<-as.factor(di.locs$pop)

di.heat<-stamppNeisD(di.gen, pop = TRUE)
colnames(di.heat)<-rownames(di.heat)
di.heat <- reshape::melt(di.heat)
ggplot(data = di.heat, aes(x=X1, y=X2, fill=value)) + 
  geom_tile()+
  scale_fill_gradient2(low = "white", high = "red", space = "Lab", name="Nei's D") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#zoom in on solomons
di.sol.gen<-new("genlight",(as.matrix(di.gen)[c(1:15,19:27), ]))
di.sol.locs<-di.locs[c(1:15,19:27),]
di.sol.gen@pop<-as.factor(di.sol.locs$pop)

di.sol.heat<-stamppNeisD(di.sol.gen, pop = TRUE)
colnames(di.sol.heat)<-rownames(di.sol.heat)
di.sol.heat <- reshape::melt(di.sol.heat)
ggplot(data = di.sol.heat, aes(x=X1, y=X2, fill=value)) + 
  geom_tile()+
  scale_fill_gradient2(low = "white", high = "red", space = "Lab", name="Nei's D") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


