---
title: "Hippo species delimitation"
author: "Devon DeRaad"
date: "3/27/2021"
output: html_document
---

```{r}
library(adegenet)
library(randomForest)
library(PCDimension)
library(mclust)
library(cluster)
library(MASS)
library(factoextra)
library(tsne)
library(vcfR)
library(ggforce)

#read in vcf as vcfR
vcfR <- read.vcfR("~/Desktop/hipposideros/filtered.vcf.gz")
dim(vcfR@gt)
#filter out SNPs with missing data
vcfR@fix<-vcfR@fix[rowSums(is.na(vcfR@gt)) == 0,]
vcfR@gt<-vcfR@gt[rowSums(is.na(vcfR@gt)) == 0,]
vcfR #28 samples and ~15K SNPs with no missing data

#convert vcfR into a 'genind' object
data<-vcfR2genind(vcfR)

#scale the genind
data_scaled <- scaleGen(data, center=FALSE, scale=FALSE, NA.method=c("mean"), nf)
data_scaled <- scaleGen(data, center=FALSE, scale=FALSE)

```

```{r}
###############################################
###############################################
# PCA
###############################################
###############################################

# PCA, can adjust nf to include more components
pca1 <- dudi.pca(data_scaled, center=FALSE, scale=FALSE, scannf=FALSE, nf=10)
# PCA with groups by island and species
plot.df<-pca1$li[,c(1:2)]
colnames(plot.df)<-c("PC1","PC2")
x<-gsub(".*_H_","",rownames(plot.df))
x[27:28]<-"diadema_PNG"
plot.df$island<-x
ggplot(data=plot.df, aes(x=PC1, y=PC2, col=island))+
  geom_point(cex=3)+
  theme_classic()

# pam clustering on pca output
for (i in 2:20){
  print(paste(i, mean(silhouette(pam(pca1$li, i))[, "sil_width"])))
}
#prefers 10 groups
pam.pc<-pam(pca1$li, 10)
plot.df$pam.pc<-as.factor(pam.pc$clustering)
#plot with color = island and circles showing pam PCA clustering
ggplot(data=plot.df, aes(x=PC1, y=PC2, col=island))+
  geom_mark_ellipse(aes(label = pam.pc)) +
  geom_point(cex=3)+
  theme_classic()

# determine optimal k of PCA via hierarchical clustering with BIC using mclust
# adjust G option to reasonable potential cluster values, e.g. for up to 12 clusters, G=1:12
pca_clust <- Mclust(pca1$li, G=1:20)
pca_clust$classification
#wants 18 groups
```

```{r}
###############################################
###############################################
# into the Random Forest, unsupervised
###############################################
###############################################

# convert genind scaled data to factors for randomForest
data_conv <- as.data.frame(data_scaled)
data_conv[is.na(data_conv)] <- ""
data_conv[sapply(data_conv, is.integer)] <- lapply(data_conv[sapply(data_conv, is.integer)], as.factor)
data_conv[sapply(data_conv, is.character)] <- lapply(data_conv[sapply(data_conv, is.character)], as.factor)
nsamp <- nrow(data_conv)

# unsupervised random forest
rftest <- randomForest(data_conv, ntree=5000)
#rftest <- randomForest(pca1$tab, ntree=500)
#rftest <- randomForest(data_scaled, ntree=500)

###############
# classic MDS
###############
# cMDS with optimal number of components to retain using broken-stick
cmdsplot1 <- MDSplot(rf=rftest, fac=plot.df$pam.pc, k=20) # may need to adjust number of dimensions if given error
cmdsplot_bstick <- PCDimension::bsDimension(cmdsplot1$eig)
cmdsplot2 <- MDSplot(rftest, plot.df$pam.pc, cmdsplot_bstick)

#cMDS plot from random forest run with the 10 groups identified by dapc labeled
cmds<-as.data.frame(cmdsplot2$points)
plot.df$rf.cmds1<-cmdsplot2$points[,1]
plot.df$rf.cmds2<-cmdsplot2$points[,2]

# pam clustering on cMDS output
for (i in 2:20){
  print(paste(i, mean(silhouette(pam(cmdsplot1$points, i))[, "sil_width"])))
}
#prefers 7 groups, matching dapc
DAPC_pam_clust_prox <- pam(cmdsplot1$points, 7)
plot.df$rf.cmds.pam<-DAPC_pam_clust_prox$clustering

#plot with color = island and circles showing pam PCA clustering
ggplot(data=plot.df, aes(x=rf.cmds1, y=rf.cmds2, col=island))+
  geom_mark_ellipse(aes(label = rf.cmds.pam)) +
  geom_point(cex=3)+
  theme_classic()

# determine optimal k from cMDS via hierarchical clustering with BIC
# adjust G option to reasonable potential cluster values, e.g. for up to 12 clusters, G=1:12
cmdsplot_clust <- Mclust(cmdsplot2$points)
cmdsplot_clust$classification
#hierarchical clustering of random forest identifies 9 groups 

# cMDS with optimal k and clusters of RF via hierarchical clustering
plot.df$rf.cmds.mclust<-as.factor(cmdsplot_clust$classification)
ggplot(data=plot.df, aes(x=rf.cmds1, y=rf.cmds2, col=island))+
  geom_mark_ellipse(aes(label = rf.cmds.mclust)) +
  geom_point(cex=3)+
  theme_classic()

```

```{r}
###############################################
###############################################
# t-SNE
###############################################
###############################################

# prepare plot labels and such
# this makes it so it is grouped by DAPC clusters
colors = rainbow(length(unique(pam.pc)))
names(colors) = unique(pam.pc)
ecb = function(x,y){plot(x,t='n'); text(x, labels=pam.pc, col=colors[pam.pc])}

# t-SNE on principal components of scaled data
# adjust perplexity, initial_dims
# can do k=3 for 3D plot
# should do only <50 variables
# can do it on pca$li (if you reduce the number of components), or on cmdsplot2$points
tsne_p5 = tsne(cmdsplot2$points, max_iter=5000, perplexity=5, initial_dims=5)

#add tsne coordinates to plotting df
plot.df$tsne.1<-tsne_p5[,1]
plot.df$tsne.2<-tsne_p5[,2]

# pam clustering
for (i in 2:20){
  print(paste(i, mean(silhouette(pam(tsne_p5, i))[, "sil_width"])))
}
#pam prefers 7 groups
tsne.pam<-pam(tsne_p5, 7)

# tsne with optimal k and clustering identified via PAM
plot.df$tsne.pam<-as.factor(tsne.pam$clustering)
ggplot(data=plot.df, aes(x=tsne.1, y=tsne.2, col=island))+
  geom_mark_ellipse(aes(label = tsne.pam)) +
  geom_point(cex=3)+
  theme_classic()

# determine optimal k of tSNE via hierarchical clustering with BIC
# adjust G option to reasonable potential cluster values, e.g. for up to 12 clusters, G=1:12
tsne_p5_clust <- Mclust(tsne_p5)
tsne_p5_clust$classification

# tsne with optimal k and clustering identified via PAM
plot.df$tsne.mclust<-as.factor(tsne_p5_clust$classification)
ggplot(data=plot.df, aes(x=tsne.1, y=tsne.2, col=island))+
  geom_mark_ellipse(aes(label = tsne.mclust)) +
  geom_point(cex=3)+
  theme_classic()


```

```{r}
#bring in latent space coordinates from VAE and do clustering analysis here:
#pseudocode:
#read.table(vae)
#add vae latent space dimensions to plot.data

## pam clustering
#for (i in 2:20){
#  print(paste(i, mean(silhouette(pam(vae, i))[, "sil_width"])))
#}
##pam prefers  groups
#vae.pam<-pam(vae, 7)
#
## vae with optimal k and clustering identified via PAM
#plot.df$vae.pam<-as.factor(vae.pam$clustering)
#ggplot(data=plot.df, aes(x=vae.1, y=vae.2, col=island))+
#  geom_mark_ellipse(aes(label = vae.pam)) +
#  geom_point(cex=3)+
#  theme_classic()
#
## determine optimal k of vae via hierarchical clustering with BIC
## adjust G option to reasonable potential cluster values, e.g. for up to 12 clusters, G=1:12
#vae_clust <- Mclust(vae_p5)
#vae_clust$classification
#
## tsne with optimal k and clustering identified via PAM
#plot.df$vae.mclust<-as.factor(vae_clust$classification)
#ggplot(data=plot.df, aes(x=vae.1, y=vae.2, col=island))+
#  geom_mark_ellipse(aes(label = vae.mclust)) +
#  geom_point(cex=3)+
#  theme_classic()


```


